### ISSUE TITLE
لینک فیلم دوره مشکل داره

### ISSUE THREAD

**Issue by nimaJbin** [ssc-public/Web-Programming#1]
سلام خسته نباشید
لینک فیلم دوره در آپارات 404 میده
ممنون میشم بررسی کنید.

https://github.com/shrif-web/handout/blob/0b98a23c7f51ca03cb327fa2d406df140f598e03/ReactWorkshop.md?plain=1#L30

**Comment by AmooHashem** [comment]
سلام!
منظورت این فیلمه؟ https://www.aparat.com/v/ckCv1
این که کار می‌کنه
